//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrackerDotNet
{
    public partial class UserInformation
    {
        protected global::System.Web.UI.WebControls.Content HeadContent;
        protected global::System.Web.UI.WebControls.Content MainContent;
        protected global::System.Web.UI.WebControls.CheckBox cbxUserIsApproved;
        protected global::System.Web.UI.WebControls.Label lblUserLockedOut;
        protected global::System.Web.UI.WebControls.Button btnUnlockUser;
        protected global::System.Web.UI.WebControls.Button btnDeleteUser;
        protected global::System.Web.UI.WebControls.Button btnUpdate;
        protected global::System.Web.UI.WebControls.Button btnReturnToManagerUser;
    }
}
