//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrackerDotNet
{
    public partial class DisableClient
    {
        protected global::System.Web.UI.WebControls.Label CompanyNameLabel;
    }
}
