//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrackerDotNet
{
    public partial class MobileSite
    {
        protected global::System.Web.UI.WebControls.ContentPlaceHolder HeadContent;
        protected global::System.Web.UI.WebControls.HyperLink hlHome;
        protected global::System.Web.UI.WebControls.HyperLink hlDeliveries;
        protected global::System.Web.UI.WebControls.HyperLink hlRepairs;
        protected global::System.Web.UI.WebControls.ContentPlaceHolder MainContent;
    }
}
