//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrackerDotNet
{
    public partial class Print
    {
        protected global::System.Web.UI.WebControls.ContentPlaceHolder HeadContent;
        protected global::System.Web.UI.WebControls.Image imgQuaffeeLogo;
        protected global::System.Web.UI.WebControls.ContentPlaceHolder MainContent;
    }
}
