//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrackerDotNet.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TrackerDotNet.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FINAL NOTICE: This is your last reminder before your account will be suspended. Please respond immediately.
        ///.
        /// </summary>
        public static string CoffeeCheckup_BodyFinalWarning {
            get {
                return ResourceManager.GetString("CoffeeCheckup.BodyFinalWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FINAL NOTICE: This is your last reminder before your account will be suspended. Please respond immediately.
        ///
        ///.
        /// </summary>
        public static string CoffeeCheckupBodyFinalWarning {
            get {
                return ResourceManager.GetString("CoffeeCheckupBodyFinalWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a{0} {1}, please respond to cancel..
        /// </summary>
        public static string CoffeeCheckupBodyOrderType {
            get {
                return ResourceManager.GetString("CoffeeCheckupBodyOrderType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We will only place an order on your request, no order has been added, this just a reminder..
        /// </summary>
        public static string CoffeeCheckupBodyReminderOnly {
            get {
                return ResourceManager.GetString("CoffeeCheckupBodyReminderOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coffee Checkup Status.
        /// </summary>
        public static string CoffeeCheckupDialogEmailStatusTitle {
            get {
                return ResourceManager.GetString("CoffeeCheckupDialogEmailStatusTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Recurring Item Last Date.
        /// </summary>
        public static string CoffeeCheckupDialogRecurringDateTitle {
            get {
                return ResourceManager.GetString("CoffeeCheckupDialogRecurringDateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temp Table Operation.
        /// </summary>
        public static string CoffeeCheckupDialogTempTableTitle {
            get {
                return ResourceManager.GetString("CoffeeCheckupDialogTempTableTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to send some emails in batch: {0}.
        /// </summary>
        public static string CoffeeCheckupErrorBatchEmailFailure {
            get {
                return ResourceManager.GetString("CoffeeCheckupErrorBatchEmailFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Sending Error.
        /// </summary>
        public static string CoffeeCheckupErrorEmailSending {
            get {
                return ResourceManager.GetString("CoffeeCheckupErrorEmailSending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error inserting order for: {0}.
        /// </summary>
        public static string CoffeeCheckupErrorOrderInsert {
            get {
                return ResourceManager.GetString("CoffeeCheckupErrorOrderInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not set the recurring last date.
        /// </summary>
        public static string CoffeeCheckupErrorRecurringDateFailure {
            get {
                return ResourceManager.GetString("CoffeeCheckupErrorRecurringDateFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error deleting old temp tables.
        /// </summary>
        public static string CoffeeCheckupErrorTempTableDelete {
            get {
                return ResourceManager.GetString("CoffeeCheckupErrorTempTableDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error adding some records to temp table.
        /// </summary>
        public static string CoffeeCheckupErrorTempTableInsert {
            get {
                return ResourceManager.GetString("CoffeeCheckupErrorTempTableInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;br /&gt;&lt;br /&gt;If you would prefer to be disabled then click &lt;a href=&apos;{0}/DisableClient.aspx?CoID={1}&amp;amp;token={2}&apos;&gt;disable me&lt;/a&gt;.
        /// </summary>
        public static string CoffeeCheckupFooterDisableLink {
            get {
                return ResourceManager.GetString("CoffeeCheckupFooterDisableLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orders have been automatically created for the items listed above. These will be processed on your next delivery day..
        /// </summary>
        public static string CoffeeCheckupFooterOrderAdded {
            get {
                return ResourceManager.GetString("CoffeeCheckupFooterOrderAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;br /&gt;&lt;br /&gt;Internal: Order Ref &lt;a href=&apos;{0}/{1}&apos;&gt;here&lt;/a&gt;..
        /// </summary>
        public static string CoffeeCheckupFooterOrderLink {
            get {
                return ResourceManager.GetString("CoffeeCheckupFooterOrderLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Hi Coffee Lover,&lt;/p&gt;.
        /// </summary>
        public static string CoffeeCheckupGreetingGeneric {
            get {
                return ResourceManager.GetString("CoffeeCheckupGreetingGeneric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Hi {0},&lt;/p&gt;.
        /// </summary>
        public static string CoffeeCheckupGreetingWithName {
            get {
                return ResourceManager.GetString("CoffeeCheckupGreetingWithName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;td style=&apos;background-color: #CFEFC9; color: #694030; font-weight: bold&apos;&gt;{0}&lt;/td&gt;.
        /// </summary>
        public static string CoffeeCheckupHtmlTableCellAlt {
            get {
                return ResourceManager.GetString("CoffeeCheckupHtmlTableCellAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;td style=&apos;background-color: #E9FFE0; color: #593020; font-weight: bold&apos;&gt;{0}&lt;/td&gt;.
        /// </summary>
        public static string CoffeeCheckupHtmlTableCellNormal {
            get {
                return ResourceManager.GetString("CoffeeCheckupHtmlTableCellNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;thead&gt;&lt;tr&gt;&lt;td style=&apos;background-color: #EFFFE9; font-weight: bold&apos;&gt;{0}&lt;/td&gt;&lt;td style=&apos;background-color: #EFFFE9;&apos; colspan=&apos;2&apos;&gt;{1}&lt;/td&gt;&lt;/thead&gt;.
        /// </summary>
        public static string CoffeeCheckupHtmlTableHeader {
            get {
                return ResourceManager.GetString("CoffeeCheckupHtmlTableHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;tr&gt;&lt;td style=&apos;background-color: #CFEFC9; color: #694030; font-weight: bold&apos;&gt;{0}&lt;/td&gt;&lt;td style=&apos;background-color: #CFEFC9&apos;&gt;{1}&lt;/td&gt;&lt;td style=&apos;background-color: #CFEFC9&apos;&gt;{2}&lt;/td&gt;&lt;/tr&gt;.
        /// </summary>
        public static string CoffeeCheckupHtmlTableRowAlt {
            get {
                return ResourceManager.GetString("CoffeeCheckupHtmlTableRowAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;tr&gt;&lt;td style=&apos;background-color: #E9FFE0; color: #593020; font-weight: bold&apos;&gt;{0}&lt;/td&gt;&lt;td style=&apos;background-color: #E9FFE0&apos;&gt;{1}&lt;/td&gt;&lt;td style=&apos;background-color: #E9FFE0&apos;&gt;{2}&lt;/td&gt;&lt;/tr&gt;.
        /// </summary>
        public static string CoffeeCheckupHtmlTableRowNormal {
            get {
                return ResourceManager.GetString("CoffeeCheckupHtmlTableRowNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table border=&apos;0&apos; style=&apos;border: 1px solid&apos;&gt;&lt;tbody&gt;.
        /// </summary>
        public static string CoffeeCheckupHtmlTableStart {
            get {
                return ResourceManager.GetString("CoffeeCheckupHtmlTableStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-fulfill order.
        /// </summary>
        public static string CoffeeCheckupOrderTypeAutoFulfill {
            get {
                return ResourceManager.GetString("CoffeeCheckupOrderTypeAutoFulfill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-fulfill and recurring order.
        /// </summary>
        public static string CoffeeCheckupOrderTypeCombined {
            get {
                return ResourceManager.GetString("CoffeeCheckupOrderTypeCombined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recurring order.
        /// </summary>
        public static string CoffeeCheckupOrderTypeRecurring {
            get {
                return ResourceManager.GetString("CoffeeCheckupOrderTypeRecurring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a reminder only.
        /// </summary>
        public static string CoffeeCheckupOrderTypeReminderOnly {
            get {
                return ResourceManager.GetString("CoffeeCheckupOrderTypeReminderOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email batch partially sent: {0} successful, {1} failed.
        /// </summary>
        public static string CoffeeCheckupStatusBatchSendPartial {
            get {
                return ResourceManager.GetString("CoffeeCheckupStatusBatchSendPartial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email batch sent successfully to {0} recipients.
        /// </summary>
        public static string CoffeeCheckupStatusBatchSendSuccess {
            get {
                return ResourceManager.GetString("CoffeeCheckupStatusBatchSendSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reminders processed: {0} sent, {1} failed.
        /// </summary>
        public static string CoffeeCheckupStatusRemindersProcessed {
            get {
                return ResourceManager.GetString("CoffeeCheckupStatusRemindersProcessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coffee delivery update for your consideration.
        /// </summary>
        public static string CoffeeCheckupSubjectAutoFulfill {
            get {
                return ResourceManager.GetString("CoffeeCheckupSubjectAutoFulfill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your coffee order and delivery update.
        /// </summary>
        public static string CoffeeCheckupSubjectCombined {
            get {
                return ResourceManager.GetString("CoffeeCheckupSubjectCombined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your regular coffee order is ready for review.
        /// </summary>
        public static string CoffeeCheckupSubjectRecurring {
            get {
                return ResourceManager.GetString("CoffeeCheckupSubjectRecurring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friendly coffee supply reminder.
        /// </summary>
        public static string CoffeeCheckupSubjectReminderOnly {
            get {
                return ResourceManager.GetString("CoffeeCheckupSubjectReminderOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company/Contact.
        /// </summary>
        public static string CoffeeCheckupTableCompanyContact {
            get {
                return ResourceManager.GetString("CoffeeCheckupTableCompanyContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;List of Items&lt;/b&gt;.
        /// </summary>
        public static string CoffeeCheckupTableListOfItems {
            get {
                return ResourceManager.GetString("CoffeeCheckupTableListOfItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next estimate dispatch date.
        /// </summary>
        public static string CoffeeCheckupTableNextDispatchDate {
            get {
                return ResourceManager.GetString("CoffeeCheckupTableNextDispatchDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next estimate prep date.
        /// </summary>
        public static string CoffeeCheckupTableNextPrepDate {
            get {
                return ResourceManager.GetString("CoffeeCheckupTableNextPrepDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string CoffeeCheckupTableType {
            get {
                return ResourceManager.GetString("CoffeeCheckupTableType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer {0} (ID: {1}) has been disabled..
        /// </summary>
        public static string CustomerDisabled {
            get {
                return ResourceManager.GetString("CustomerDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer {0} (ID: {1}) has been disabled via self-service request..
        /// </summary>
        public static string CustomerDisabledViaSelfService {
            get {
                return ResourceManager.GetString("CustomerDisabledViaSelfService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error disabling customer {0}: {1}.
        /// </summary>
        public static string CustomerDisableError {
            get {
                return ResourceManager.GetString("CustomerDisableError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;br /&gt;
        ///Kind regards,&lt;br /&gt;
        ///&lt;b&gt;The Quaffee Team&lt;/b&gt;&lt;br /&gt;
        ///📧 &lt;a href=&apos;mailto:orders@quaffee.co.za&apos;&gt;orders@quaffee.co.za&lt;/a&gt;&lt;br /&gt;
        ///🌐 &lt;a href=&apos;http://www.quaffee.co.za&apos;&gt;www.quaffee.co.za&lt;/a&gt;&lt;br /&gt;.
        /// </summary>
        public static string DefaultEmailSignature {
            get {
                return ResourceManager.GetString("DefaultEmailSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;br /&gt;
        ///Kind regards,&lt;br /&gt;
        ///&lt;b&gt;The Quaffee Team&lt;/b&gt;&lt;br /&gt;
        ///📧 &lt;a href=&apos;mailto:orders@quaffee.co.za&apos;&gt;orders@quaffee.co.za&lt;/a&gt;&lt;br /&gt;
        ///🌐 &lt;a href=&apos;http://www.quaffee.co.za&gt;quaffee.co.za&lt;/a&gt;&lt;br /&gt;.
        /// </summary>
        public static string DefaultEmailSignatureNoUser {
            get {
                return ResourceManager.GetString("DefaultEmailSignatureNoUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As requested we have disabled: {0} in Quaffee&apos;s Coffee Tracker..
        /// </summary>
        public static string DisableClientDisabledMessage {
            get {
                return ResourceManager.GetString("DisableClientDisabledMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We wish you the best in the future. Should you require anything else from us please email {0}..
        /// </summary>
        public static string DisableClientFutureMessage {
            get {
                return ResourceManager.GetString("DisableClientFutureMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear {0},.
        /// </summary>
        public static string DisableClientGreeting {
            get {
                return ResourceManager.GetString("DisableClientGreeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company not found or invalid request.
        /// </summary>
        public static string DisableClientNotFound {
            get {
                return ResourceManager.GetString("DisableClientNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid request detected.
        /// </summary>
        public static string DisableClientSecurityError {
            get {
                return ResourceManager.GetString("DisableClientSecurityError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} request to be disabled in Coffee Tracker.
        /// </summary>
        public static string DisableClientSubject {
            get {
                return ResourceManager.GetString("DisableClientSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You’ve selected collection. Your order will be ready on: {0}..
        /// </summary>
        public static string OrderCollectionNote {
            get {
                return ResourceManager.GetString("OrderCollectionNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear {0},&lt;br /&gt;We confirm the following order:.
        /// </summary>
        public static string OrderConfirmationIntro {
            get {
                return ResourceManager.GetString("OrderConfirmationIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Details:.
        /// </summary>
        public static string OrderConfirmationLineIntro {
            get {
                return ResourceManager.GetString("OrderConfirmationLineIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This order has purchase order: {0}, allocated to it..
        /// </summary>
        public static string OrderConfirmationPOReceived {
            get {
                return ResourceManager.GetString("OrderConfirmationPOReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;NOTE&lt;/b&gt;: We&apos;re still waiting for your Purchase Order number. Please send it at your earliest convenience..
        /// </summary>
        public static string OrderConfirmationPORequired {
            get {
                return ResourceManager.GetString("OrderConfirmationPORequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Quaffee Order Confirmation.
        /// </summary>
        public static string OrderConfirmationSubject {
            get {
                return ResourceManager.GetString("OrderConfirmationSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your order will be sent via courier on: {0}..
        /// </summary>
        public static string OrderCourierNote {
            get {
                return ResourceManager.GetString("OrderCourierNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We’ll deliver your order on: {0}..
        /// </summary>
        public static string OrderDeliveryNote {
            get {
                return ResourceManager.GetString("OrderDeliveryNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;br /&gt;This confirmation was generated automatically by Quaffee’s order and tracking system.&lt;br /&gt;.
        /// </summary>
        public static string OrderEmailFooter {
            get {
                return ResourceManager.GetString("OrderEmailFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;li&gt;{0} of {1}&lt;/li&gt;.
        /// </summary>
        public static string OrderItemFormatBasic {
            get {
                return ResourceManager.GetString("OrderItemFormatBasic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;li&gt;{0} of {1} - Preparation note: {2}&lt;/li&gt;.
        /// </summary>
        public static string OrderItemFormatWithPrep {
            get {
                return ResourceManager.GetString("OrderItemFormatWithPrep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear {0},&lt;br /&gt;Your order has been collected — thank you!.
        /// </summary>
        public static string OrderStatusCollected {
            get {
                return ResourceManager.GetString("OrderStatusCollected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear {0},&lt;br /&gt;Your order has been successfully delivered and signed for..
        /// </summary>
        public static string OrderStatusDelivered {
            get {
                return ResourceManager.GetString("OrderStatusDelivered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear {0},&lt;br /&gt;Your order has left our premises and is now enroute to you..
        /// </summary>
        public static string OrderStatusDispatched {
            get {
                return ResourceManager.GetString("OrderStatusDispatched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  &lt;br /&gt;Thank you for your continued support.&lt;br /&gt;.
        /// </summary>
        public static string OrderStatusFooter {
            get {
                return ResourceManager.GetString("OrderStatusFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear {0},&lt;br /&gt;Your order has been placed in your post box and is ready for you..
        /// </summary>
        public static string OrderStatusPostbox {
            get {
                return ResourceManager.GetString("OrderStatusPostbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quaffee Order Status Update.
        /// </summary>
        public static string OrderStatusSubject {
            get {
                return ResourceManager.GetString("OrderStatusSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error updating the repair.
        /// </summary>
        public static string RepairErrorUpdating {
            get {
                return ResourceManager.GetString("RepairErrorUpdating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear {0},&lt;br /&gt;&lt;br /&gt;
        ///We wanted to let you know that the repair status of your &lt;b&gt;{1}&lt;/b&gt; (serial number: &lt;b&gt;{2}&lt;/b&gt;) has been updated to: &lt;b&gt;{3}&lt;/b&gt;.&lt;br /&gt;&lt;br /&gt;
        ///You&apos;re receiving this message because your email address is linked to this repair.&lt;br /&gt;&lt;br /&gt;
        ///
        ///Please note:&lt;br /&gt;
        ///Quaffee does not operate a dedicated repair workshop. As a service to our coffee clients, we deliver machines to external partners, provide swap-out units when available, and apply a workshop fee plus a small admin charge.&lt;br /&gt;&lt; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string RepairStatusEmailBody {
            get {
                return ResourceManager.GetString("RepairStatusEmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Your Repair Status Has Changed.
        /// </summary>
        public static string RepairStatusEmailSubject {
            get {
                return ResourceManager.GetString("RepairStatusEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repair status updated successfully and notification sent..
        /// </summary>
        public static string RepairStatusUpdateSuccess {
            get {
                return ResourceManager.GetString("RepairStatusUpdateSuccess", resourceCulture);
            }
        }
    }
}
