//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrackerDotNet
{
    public partial class Login
    {
        protected global::System.Web.UI.WebControls.Content HeaderContent;
        protected global::System.Web.UI.WebControls.Content BodyContent;
        protected global::System.Web.UI.WebControls.HyperLink RegisterHyperLink;
        protected global::System.Web.UI.WebControls.Login LoginUser;
        protected global::System.Web.UI.WebControls.Literal FailureText;
        protected global::System.Web.UI.WebControls.ValidationSummary LoginUserValidationSummary;
        protected global::System.Web.UI.WebControls.Label UserNameLabel;
        protected global::System.Web.UI.WebControls.TextBox UserName;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator UserNameRequired;
        protected global::System.Web.UI.WebControls.Label PasswordLabel;
        protected global::System.Web.UI.WebControls.TextBox Password;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator PasswordRequired;
        protected global::System.Web.UI.WebControls.CheckBox RememberMe;
        protected global::System.Web.UI.WebControls.Label RememberMeLabel;
        protected global::System.Web.UI.WebControls.Button LoginButton;
    }
}
