//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrackerDotNet
{
    public partial class CustomerDetails
    {
        /*
        protected global::System.Web.UI.WebControls.Content HeadContent;
        protected global::System.Web.UI.WebControls.Content MainContent;
        protected global::System.Web.UI.WebControls.Label lblCustomerID;
        protected global::System.Web.UI.WebControls.ScriptManager smCustomerDetails;
        protected global::System.Web.UI.WebControls.UpdateProgress uprgCustomerDetails;
        protected global::System.Web.UI.WebControls.UpdatePanel upnlCustomerDetails;
        protected global::System.Web.UI.WebControls.TextBox CompanyNameTextBox;
        protected global::System.Web.UI.WebControls.Label CompanyIDLabel;
        protected global::System.Web.UI.WebControls.TextBox ContactFirstNameTextBox;
        protected global::System.Web.UI.WebControls.TextBox ContactLastNameTextBox;
        protected global::System.Web.UI.WebControls.TextBox ContactTitleTextBox;
        protected global::System.Web.UI.WebControls.TextBox ContactAltFirstNameTextBox;
        protected global::System.Web.UI.WebControls.TextBox ContactAltLastNameTextBox;
        protected global::System.Web.UI.WebControls.TextBox BillingAddressTextBox;
        protected global::System.Web.UI.WebControls.TextBox DepartmentTextBox;
        protected global::System.Web.UI.WebControls.TextBox PostalCodeTextBox;
        protected global::System.Web.UI.WebControls.DropDownList ddlCities;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidatorddlCities;
        protected global::System.Web.UI.WebControls.TextBox ProvinceTextBox;
        protected global::System.Web.UI.WebControls.TextBox PhoneNumberTextBox;
        protected global::System.Web.UI.WebControls.TextBox CellNumberTextBox;
        protected global::System.Web.UI.WebControls.TextBox FaxNumberTextBox;
        protected global::System.Web.UI.WebControls.TextBox EmailAddressTextBox;
        protected global::System.Web.UI.WebControls.TextBox AltEmailAddressTextBox;
        protected global::System.Web.UI.WebControls.DropDownList ddlCustomerTypes;
        protected global::System.Web.UI.WebControls.DropDownList ddlEquipTypes;
        protected global::System.Web.UI.WebControls.TextBox MachineSNTextBox;
        protected global::System.Web.UI.WebControls.DropDownList ddlFirstPreference;
        protected global::System.Web.UI.WebControls.TextBox PriPrefQtyTextBox;
        protected global::System.Web.UI.WebControls.DropDownList ddlPackagingTypes;
        protected global::System.Web.UI.WebControls.DropDownList ddlDeliveryBy;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator ddlDeliveryByRequiredFieldValidator;
        protected global::System.Web.UI.WebControls.DropDownList ddlAgent;
        protected global::System.Web.UI.WebControls.Label ReminderCountLabel;
        protected global::System.Web.UI.WebControls.Label LastReminderLabel;
        protected global::System.Web.UI.WebControls.CheckBox enabledCheckBox;
        protected global::System.Web.UI.WebControls.CheckBox autofulfillCheckBox;
        protected global::System.Web.UI.WebControls.CheckBox UsesFilterCheckBox;
        protected global::System.Web.UI.WebControls.CheckBox PredictionDisabledCheckBox;
        protected global::System.Web.UI.WebControls.CheckBox AlwaysSendChkUpCheckBox;
        protected global::System.Web.UI.WebControls.CheckBox NormallyRespondsCheckBox;
        protected global::System.Web.UI.WebControls.TextBox NotesTextBox;
        protected global::System.Web.UI.WebControls.Button btnUpdate;
        protected global::System.Web.UI.WebControls.Button btnUpdateAndReturn;
        protected global::System.Web.UI.WebControls.Button btnInsert;
        protected global::System.Web.UI.WebControls.Button btnCopy2AccInfo;
        protected global::System.Web.UI.WebControls.Button btnAddLasOrder;
        protected global::System.Web.UI.WebControls.Button btnForceNext;
        protected global::System.Web.UI.WebControls.Button btnRecalcAverage;
        protected global::System.Web.UI.WebControls.Button btnCancel;
        protected global::System.Web.UI.WebControls.Literal ltrlStatus;
        protected global::System.Web.UI.WebControls.UpdatePanel uppnlTabContainer;
        protected global::System.Web.UI.WebControls.UpdatePanel dvCustomersAccInfoUpdatePanel;
        protected global::System.Web.UI.WebControls.TextBox accFullCoNameTextBox;
        protected global::System.Web.UI.WebControls.TextBox accCustomerVATNoTextBox;
        protected global::System.Web.UI.WebControls.DropDownList accInvoiceTypesDropDownList;
        protected global::System.Web.UI.WebControls.CheckBox accRequiresPurchOrderCheckBox;
        protected global::System.Web.UI.WebControls.CheckBox accEnabledCheckBox;
        protected global::System.Web.UI.WebControls.TextBox accBillAddr1TextBox;
        protected global::System.Web.UI.WebControls.TextBox accBillAddr2TextBox;
        protected global::System.Web.UI.WebControls.TextBox accBillAddr3TextBox;
        protected global::System.Web.UI.WebControls.TextBox accBillAddr4TextBox;
        protected global::System.Web.UI.WebControls.TextBox accBillAddr5TextBox;
        protected global::System.Web.UI.WebControls.TextBox accShipAddr1TextBox;
        protected global::System.Web.UI.WebControls.TextBox accShipAddr2TextBox;
        protected global::System.Web.UI.WebControls.TextBox accShipAddr3TextBox;
        protected global::System.Web.UI.WebControls.TextBox accShipAddr4TextBox;
        protected global::System.Web.UI.WebControls.TextBox accShipAddr5TextBox;
        protected global::System.Web.UI.WebControls.TextBox accFirstNameTextBox;
        protected global::System.Web.UI.WebControls.TextBox accLastNameTextBox;
        protected global::System.Web.UI.WebControls.TextBox accAccEmailTextBox;
        protected global::System.Web.UI.WebControls.TextBox accAltFirstNameTextBox;
        protected global::System.Web.UI.WebControls.TextBox accAltLastNameTextBox;
        protected global::System.Web.UI.WebControls.TextBox accAltEmailTextBox;
        protected global::System.Web.UI.WebControls.DropDownList accPaymentTermsDropDownList;
        protected global::System.Web.UI.WebControls.DropDownList accPriceLevelsDropDownList;
        protected global::System.Web.UI.WebControls.TextBox accRegNoTextBox;
        protected global::System.Web.UI.WebControls.TextBox accLimitTextBox;
        protected global::System.Web.UI.WebControls.TextBox accBankAccNoTextBox;
        protected global::System.Web.UI.WebControls.TextBox accBankBranchTextBox;
        protected global::System.Web.UI.WebControls.TextBox accNotesTextBox;
        protected global::System.Web.UI.WebControls.Label CustomersAccInfoIDLabel;
        protected global::System.Web.UI.WebControls.Button accAddDetailsButton;
        protected global::System.Web.UI.WebControls.Button accUpdateButton;
        protected global::System.Web.UI.WebControls.UpdatePanel upnlNextItems;
        protected global::System.Web.UI.WebControls.DataGrid dgCustomerUsage;
        protected global::System.Web.UI.WebControls.UpdateProgress updtprgItems;
        protected global::System.Web.UI.WebControls.UpdatePanel upnlItems;
        protected global::System.Web.UI.WebControls.GridView gvItems;
        protected global::System.Web.UI.WebControls.ImageButton UpdateButton;
        protected global::System.Web.UI.WebControls.ImageButton CancelButton;
        protected global::System.Web.UI.WebControls.ImageButton EditButton;
        protected global::System.Web.UI.WebControls.ImageButton DeleteButton;
        protected global::System.Web.UI.WebControls.TextBox tbxItemDate;
        protected global::System.Web.UI.WebControls.Label lblItemDate;
        protected global::System.Web.UI.WebControls.DropDownList ddlItems;
        protected global::System.Web.UI.WebControls.Label ItemDescLabel;
        protected global::System.Web.UI.WebControls.TextBox tbxAmountProvided;
        protected global::System.Web.UI.WebControls.Label lblAmountProvided;
        protected global::System.Web.UI.WebControls.DropDownList ddlPackaging;
        protected global::System.Web.UI.WebControls.Label PackagingIDLabel;
        protected global::System.Web.UI.WebControls.TextBox tbxPrepTypeID;
        protected global::System.Web.UI.WebControls.Label lblPrepTypeID;
        protected global::System.Web.UI.WebControls.TextBox tbxNotes;
        protected global::System.Web.UI.WebControls.Label lblNotes;
        protected global::System.Web.UI.WebControls.Label lblClientUsageLineNo;
        protected global::System.Web.UI.WebControls.Label lblClientUsageLineNo;
        protected global::System.Web.UI.WebControls.ObjectDataSource odsItemUsage;
        protected global::System.Web.UI.WebControls.ObjectDataSource odsCities;
        protected global::System.Web.UI.WebControls.ObjectDataSource odsItems;
        protected global::System.Web.UI.WebControls.ObjectDataSource odsEquipTypes;
        protected global::System.Web.UI.WebControls.ObjectDataSource odsCustomerTypes;
        protected global::System.Web.UI.WebControls.ObjectDataSource odsPersons;
        protected global::System.Web.UI.WebControls.ObjectDataSource odsPackagingTypes;
        protected global::System.Web.UI.WebControls.ObjectDataSource odsInvoiceTypes;
        protected global::System.Web.UI.WebControls.ObjectDataSource odsPaymentTerms;
        protected global::System.Web.UI.WebControls.ObjectDataSource odsPriceLevels;
        protected global::System.Web.UI.WebControls.ObjectDataSource dsCustomerUsage;
        */
    }
}
