//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrackerDotNet
{
    public partial class Customers
    {
        /*
        protected global::System.Web.UI.WebControls.Content HeadContent;
        protected global::System.Web.UI.WebControls.Content MainContent;
        protected global::System.Web.UI.WebControls.ScriptManager smCustomerSummary;
        protected global::System.Web.UI.WebControls.UpdateProgress uprgCustomerSummary;
        protected global::System.Web.UI.WebControls.UpdatePanel upnlSelection;
        protected global::System.Web.UI.WebControls.DropDownList ddlFilterBy;
        protected global::System.Web.UI.WebControls.TextBox tbxFilterBy;
        protected global::System.Web.UI.WebControls.Button btnGon;
        protected global::System.Web.UI.WebControls.Button btnReset;
        protected global::System.Web.UI.WebControls.DropDownList ddlCustomerEnabled;
        protected global::System.Web.UI.WebControls.UpdatePanel upnlCustomerSummary;
        protected global::System.Web.UI.WebControls.GridView gvCustomers;
        protected global::System.Web.UI.WebControls.ObjectDataSource odsCustomerSummarys;
        protected global::System.Web.UI.WebControls.Label lblFilter;
        */
    }
}
