//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrackerDotNet
{
    public partial class DeliverySheet
    {
        /*
        protected global::System.Web.UI.WebControls.Content HeadContent;
        protected global::System.Web.UI.WebControls.Content MainContent;
        protected global::System.Web.UI.WebControls.ScriptManager smDelivery;
        protected global::System.Web.UI.WebControls.Panel pnlDeliveryDate;
        protected global::System.Web.UI.WebControls.UpdatePanel upnlDeliveryFilterBy;
        protected global::System.Web.UI.WebControls.DropDownList ddlActiveRoastDates;
        protected global::System.Web.UI.WebControls.Button btnGo;
        protected global::System.Web.UI.WebControls.Button btnRefresh;
        protected global::System.Web.UI.WebControls.Label lblDeliveryBy;
        protected global::System.Web.UI.WebControls.DropDownList ddlDeliveryBy;
        protected global::System.Web.UI.WebControls.TextBox tbxFindClient;
        protected global::System.Web.UI.WebControls.Button btnFind;
        protected global::System.Web.UI.WebControls.Button btnPrint;
        protected global::System.Web.UI.WebControls.HyperLink hlAddDeliveryItem;
        protected global::System.Web.UI.WebControls.ObjectDataSource odsActiveRoastDates;
        protected global::System.Web.UI.WebControls.UpdatePanel upnlDeliveryItems;
        protected global::System.Web.UI.WebControls.Table tblDeliveries;
        protected global::System.Web.UI.WebControls.Table tblTotals;
        protected global::System.Web.UI.WebControls.Label ltrlWhichDate;
        */
    }
}
