//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrackerDotNet
{
    public partial class ItemGroups
    {
        /*
        protected global::System.Web.UI.WebControls.Content HeadContent;
        protected global::System.Web.UI.WebControls.Content MainContent;
        protected global::System.Web.UI.WebControls.ScriptManager scrmngItemGroups;
        protected global::System.Web.UI.WebControls.UpdatePanel updtPnlItems;
        protected global::System.Web.UI.WebControls.DropDownList ddlGroupItems;
        protected global::System.Web.UI.WebControls.UpdateProgress uprgItemGroups;
        protected global::System.Web.UI.WebControls.UpdatePanel updtPnlItemsInList;
        protected global::System.Web.UI.WebControls.GridView gvItemsInList;
        protected global::System.Web.UI.WebControls.CheckBox cbxRemoveItem;
        protected global::System.Web.UI.WebControls.DropDownList ddlItemDesc;
        protected global::System.Web.UI.WebControls.Label lblItemSortPos;
        protected global::System.Web.UI.WebControls.Button btnAddItem;
        protected global::System.Web.UI.WebControls.Button btnRemove;
        protected global::System.Web.UI.WebControls.GridView gvItemsNotInGroup;
        protected global::System.Web.UI.WebControls.CheckBox cbxAddItem;
        protected global::System.Web.UI.WebControls.DropDownList ddlItemTypeDesc;
        protected global::System.Web.UI.WebControls.ObjectDataSource odsItemGroups;
        protected global::System.Web.UI.WebControls.ObjectDataSource odsItemsNotInGroup;
        protected global::System.Web.UI.WebControls.ObjectDataSource odsItemInGroup;
        protected global::System.Web.UI.WebControls.ObjectDataSource odsItemTypes;
        */
    }
}
