//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrackerDotNet
{
    public partial class LogTable
    {
        /*  in designer .cs file, the following directives are automatically generated
            and should not be modified manually. If you change the file contents, 
            the changes will be lost when the code is regenerated.

        protected global::System.Web.UI.WebControls.Content HeadContent;
        protected global::System.Web.UI.WebControls.Content MainContent;
        protected global::System.Web.UI.WebControls.ScriptManager smLogSummary;
        protected global::System.Web.UI.WebControls.UpdateProgress uprgLogSummary;
        protected global::System.Web.UI.WebControls.UpdatePanel upnlSelection;
        protected global::System.Web.UI.WebControls.DropDownList ddlFilterBy;
        protected global::System.Web.UI.WebControls.TextBox tbxFilterBy;
        protected global::System.Web.UI.WebControls.Button btnGo;
        protected global::System.Web.UI.WebControls.Button btnReset;
        protected global::System.Web.UI.WebControls.UpdatePanel upnlLogSummary;
        protected global::System.Web.UI.WebControls.GridView gvLog;
        protected global::System.Web.UI.WebControls.TextBox UserIDTextBox;
        protected global::System.Web.UI.WebControls.Label PersonUserNameLabel;
        protected global::System.Web.UI.WebControls.TextBox SectionIDTextBox;
        protected global::System.Web.UI.WebControls.Label SectionIDLabel;
        protected global::System.Web.UI.WebControls.TextBox TranactionTypeIDTextBox;
        protected global::System.Web.UI.WebControls.Label TranactionTypeIDLabel;
        protected global::System.Web.UI.WebControls.TextBox CustomerIDTextBox;
        protected global::System.Web.UI.WebControls.Label CustomerIDLabel;
        protected global::System.Web.UI.WebControls.ObjectDataSource odsLogTbl;
        protected global::System.Web.UI.WebControls.Label lblFilter;
        */

    }
}
