//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrackerDotNet
{
    public partial class OrderDone
    {
        /*  in designer .cs file, the following directives are automatically generated
            and should not be modified manually. If you change the file contents, 
            the changes will be lost when the code is regenerated.

        protected global::System.Web.UI.WebControls.Content HeadContent;
        protected global::System.Web.UI.WebControls.Content MainContent;
        protected global::System.Web.UI.WebControls.ScriptManager smOrderDone;
        protected global::System.Web.UI.WebControls.UpdateProgress updtprgOrderDone;
        protected global::System.Web.UI.WebControls.UpdatePanel updtpnlOrderDone;
        protected global::System.Web.UI.WebControls.Panel pnlOrderDetails;
        protected global::System.Web.UI.WebControls.FormView fvOrderDone;
        protected global::System.Web.UI.WebControls.Label CompanyNameLabel;
        protected global::System.Web.UI.WebControls.Label CustomerIDLabel;
        protected global::System.Web.UI.WebControls.TextBox ByDateTextBox;
        protected global::System.Web.UI.WebControls.Label CompanyNameLabel;
        protected global::System.Web.UI.WebControls.Label CustomerIDLabel;
        protected global::System.Web.UI.WebControls.TextBox ByDateTextBox;
        protected global::System.Web.UI.WebControls.GridView gvOrderDoeLines;
        protected global::System.Web.UI.WebControls.DropDownList ddlItemDesc;
        protected global::System.Web.UI.WebControls.DropDownList ddlItemDesc;
        protected global::System.Web.UI.WebControls.DropDownList ddlPackaging;
        protected global::System.Web.UI.WebControls.DropDownList ddlPackaging;
        protected global::System.Web.UI.WebControls.Button btnDone;
        protected global::System.Web.UI.WebControls.Button btnCancel;
        protected global::System.Web.UI.WebControls.TextBox tbxStock;
        protected global::System.Web.UI.WebControls.RadioButtonList rbtnSendConfirm;
        protected global::System.Web.UI.WebControls.TextBox tbxCount;
        protected global::System.Web.UI.WebControls.Literal ltrlStatus;
        protected global::System.Web.UI.WebControls.Panel pnlCustomerDetailsUpdated;
        protected global::System.Web.UI.WebControls.Label tbxCustomerName;
        protected global::System.Web.UI.WebControls.DataGrid dgCustomerUsage;
        protected global::System.Web.UI.WebControls.Button btnReturnToDeliveres;
        protected global::System.Web.UI.WebControls.SqlDataSource sdsOrderDoneHeader;
        protected global::System.Web.UI.WebControls.SqlDataSource sdsOrderDoneLines;
        protected global::System.Web.UI.WebControls.SqlDataSource sdsItemTypes;
        protected global::System.Web.UI.WebControls.SqlDataSource sdsPackagingTypes;
        */
    }
}
