//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrackerDotNet
{
    public partial class ReoccuringOrderDetails
    {
        /*  in designer .cs file, the following directives are automatically generated
            and should not be modified manually. If you change the file contents, 
            the changes will be lost when the code is regenerated.

        protected global::System.Web.UI.WebControls.Content HeadContent;
        protected global::System.Web.UI.WebControls.Content MainContent;
        protected global::System.Web.UI.WebControls.Label lblReoccuringOrderID;
        protected global::System.Web.UI.WebControls.ScriptManager smReoccuringOrderDetails;
        protected global::System.Web.UI.WebControls.UpdateProgress uprgReoccuringOrderDetails;
        protected global::System.Web.UI.WebControls.UpdatePanel upnlReoccuringOrderDetails;
        protected global::System.Web.UI.WebControls.DropDownList ddlCompanyName;
        protected global::System.Web.UI.WebControls.Label ReoccuringOrderIDLabel;
        protected global::System.Web.UI.WebControls.TextBox ValueTextBox;
        protected global::System.Web.UI.WebControls.DropDownList ddlReoccuranceType;
        protected global::System.Web.UI.WebControls.DropDownList ddlItemType;
        protected global::System.Web.UI.WebControls.TextBox QuantityTextBox;
        protected global::System.Web.UI.WebControls.TextBox UntilDateTextBox;
        protected global::System.Web.UI.WebControls.TextBox LastDateTextBox;
        protected global::System.Web.UI.WebControls.DropDownList ddlPackagingTypes;
        protected global::System.Web.UI.WebControls.CheckBox EnabledCheckBox;
        protected global::System.Web.UI.WebControls.TextBox NotesTextBox;
        protected global::System.Web.UI.WebControls.Label NextDateLabel;
        protected global::System.Web.UI.WebControls.Button btnUpdate;
        protected global::System.Web.UI.WebControls.Button btnUpdateAndReturn;
        protected global::System.Web.UI.WebControls.Button btnInsert;
        protected global::System.Web.UI.WebControls.Button btnDelete;
        protected global::System.Web.UI.WebControls.Button btnCancel;
        protected global::System.Web.UI.WebControls.Literal ltrlStatus;
        protected global::System.Web.UI.WebControls.SqlDataSource sdsCompanys;
        protected global::System.Web.UI.WebControls.ObjectDataSource odsItems;
        protected global::System.Web.UI.WebControls.ObjectDataSource odsReoccuranceTypes;
        protected global::System.Web.UI.WebControls.ObjectDataSource odsPackagingTypes;
        */
    }
}
