//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrackerDotNet
{
    public partial class ReoccuringOrders
    {
        /*  in designer .cs file, the following directives are automatically generated
            and should not be modified manually. If you change the file contents, 
            the changes will be lost when the code is regenerated.

        protected global::System.Web.UI.WebControls.Content HeadContent;
        protected global::System.Web.UI.WebControls.Content MainContent;
        protected global::System.Web.UI.WebControls.ScriptManager smReoccuringOrderSummary;
        protected global::System.Web.UI.WebControls.UpdateProgress uprgReoccuringOrderSummary;
        protected global::System.Web.UI.WebControls.UpdatePanel upnlSelection;
        protected global::System.Web.UI.WebControls.DropDownList ddlFilterBy;
        protected global::System.Web.UI.WebControls.TextBox tbxFilterBy;
        protected global::System.Web.UI.WebControls.Button btnGon;
        protected global::System.Web.UI.WebControls.Button btnReset;
        protected global::System.Web.UI.WebControls.DropDownList ddlReoccuringOrderEnabled;
        protected global::System.Web.UI.WebControls.UpdatePanel upnlReoccuringOrderSummary;
        protected global::System.Web.UI.WebControls.GridView gvReoccuringOrders;
        protected global::System.Web.UI.WebControls.ObjectDataSource odsReoccuringOrderSummarys;
        protected global::System.Web.UI.WebControls.Label lblFilter;

        */
    }
}
