//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrackerDotNet
{
    public partial class SendCoffeeCheckup
    {
        /*  in designer .cs file, the following directives are automatically generated
            and should not be modified manually. If you change the file contents, 
            the changes will be lost when the code is regenerated.

        protected global::System.Web.UI.WebControls.Content HeadContent;
        protected global::System.Web.UI.WebControls.Content MainContent;
        protected global::System.Web.UI.WebControls.ScriptManager smCustomerCheckup;
        protected global::System.Web.UI.WebControls.UpdateProgress uprgSendEmail;
        protected global::System.Web.UI.WebControls.UpdateProgress uprgCustomerCheckup;
        protected global::System.Web.UI.WebControls.UpdatePanel upnlSendEmail;
        protected global::System.Web.UI.WebControls.TextBox tbxEmailSubject;
        protected global::System.Web.UI.WebControls.Literal ltrlEmailTextID;
        protected global::System.Web.UI.WebControls.TextBox tbxEmailIntro;
        protected global::System.Web.UI.WebControls.TextBox tbxEmailBody;
        protected global::System.Web.UI.WebControls.TextBox tbxEmailFooter;
        protected global::System.Web.UI.WebControls.Literal ltrlStatus;
        protected global::System.Web.UI.WebControls.Button btnPrepData;
        protected global::System.Web.UI.WebControls.Button btnUpdate;
        protected global::System.Web.UI.WebControls.Button btnReload;
        protected global::System.Web.UI.WebControls.Button btnSend;
        protected global::System.Web.UI.WebControls.Button btnRefreshCustomerCheckupList;
        protected global::System.Web.UI.WebControls.UpdatePanel upnlCustomerCheckup;
        protected global::System.Web.UI.WebControls.GridView gvCustomerCheckup;
        protected global::System.Web.UI.WebControls.TextBox CityNameTextBox;
        protected global::System.Web.UI.WebControls.Label CityNameLabel;
        protected global::System.Web.UI.WebControls.UpdatePanel upnlContactItems;
        protected global::System.Web.UI.WebControls.GridView gvItemsToConfirm;
        protected global::System.Web.UI.WebControls.TextBox ItemDescTextBox;
        protected global::System.Web.UI.WebControls.Label ItemDescLabel;
        protected global::System.Web.UI.WebControls.ObjectDataSource odsContactsToSendCheckup;
        protected global::System.Web.UI.WebControls.ObjectDataSource odsContactToBeRemindedItems;

        */
    }
}
