//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrackerDotNet
{
    public partial class SentRemindersSheet
    {
        /*  in designer .cs file, the following directives are automatically generated
            and should not be modified manually. If you change the file contents, 
            the changes will be lost when the code is regenerated.

        protected global::System.Web.UI.WebControls.Content HeadContent;
        protected global::System.Web.UI.WebControls.Content MainContent;
        protected global::System.Web.UI.WebControls.ScriptManager smSentRemindersSummary;
        protected global::System.Web.UI.WebControls.UpdateProgress uprgSentRemindersSummary;
        protected global::System.Web.UI.WebControls.UpdatePanel upnlSelection;
        protected global::System.Web.UI.WebControls.DropDownList ddlFilterByDate;
        protected global::System.Web.UI.WebControls.UpdatePanel upnlSentRemindersList;
        protected global::System.Web.UI.WebControls.GridView gvSentReminders;
        protected global::System.Web.UI.WebControls.TextBox CustomerTextBox;
        protected global::System.Web.UI.WebControls.HyperLink CustomerHyperLink;
        protected global::System.Web.UI.WebControls.ObjectDataSource odsSentRemindersSummarys;
        protected global::System.Web.UI.WebControls.ObjectDataSource odsDatesSentReminder;
        protected global::System.Web.UI.WebControls.UpdatePanel UpdatePanel1;
        protected global::System.Web.UI.WebControls.Label lblFilter;
        protected global::System.Web.UI.WebControls.Label CustomerLabel;

        */
    }
}
