//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrackerDotNet
{
    public partial class MergeCustomersFromQB
    {
        protected global::System.Web.UI.WebControls.Content HeadContent;
        protected global::System.Web.UI.WebControls.Content MainContent;
        protected global::System.Web.UI.WebControls.FileUpload MergeFileUpload;
        protected global::System.Web.UI.WebControls.Button SelectImportFileButton;
        protected global::System.Web.UI.WebControls.Label StatusLabel;
        protected global::System.Web.UI.WebControls.GridView gvCustomers;
    }
}
