//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrackerDotNet
{
    public partial class MoveDeliveryDate
    {
        /*  in designer .cs file, the following directives are automatically generated
            and should not be modified manually. If you change the file contents, 
            the changes will be lost when the code is regenerated.

        protected global::System.Web.UI.WebControls.Content HeadContent;
        protected global::System.Web.UI.WebControls.Content MainContent;
        protected global::System.Web.UI.WebControls.UpdateProgress UpdateProgress1;
        protected global::System.Web.UI.WebControls.UpdatePanel upnlMoveDeliveryDate;
        protected global::System.Web.UI.WebControls.DropDownList OldDeliveryDateDDL;
        protected global::System.Web.UI.WebControls.ObjectDataSource odsCityDeliveryDates;
        protected global::System.Web.UI.WebControls.TextBox NewDeliveryDateTextBox;
        protected global::System.Web.UI.WebControls.Button btnMove;
        protected global::System.Web.UI.WebControls.Button btnCancel;
        protected global::System.Web.UI.WebControls.Literal StatusLiteral;
        protected global::System.Web.UI.WebControls.GridView gvPrepData;
        protected global::System.Web.UI.WebControls.SqlDataSource sdsCityPrepDates;

        */
    }
}
