//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrackerDotNet
{
    public partial class SystemTools
    {
        /*  in designer .cs file, the following directives are automatically generated
            and should not be modified manually. If you change the file contents, 
            the changes will be lost when the code is regenerated.

        protected global::System.Web.UI.WebControls.Content HeadContent;
        protected global::System.Web.UI.WebControls.Content MainContent;
        protected global::System.Web.UI.WebControls.ScriptManager tsmSystemTools;
        protected global::System.Web.UI.WebControls.UpdateProgress uprgSystemTools;
        protected global::System.Web.UI.WebControls.UpdatePanel upnlSystemToolsButtons;
        protected global::System.Web.UI.WebControls.Button btnSetClientType;
        protected global::System.Web.UI.WebControls.Button btnXMLTOSQL;
        protected global::System.Web.UI.WebControls.Button btnResetPrepDates;
        protected global::System.Web.UI.WebControls.Button btnMoveDlvryDate;
        protected global::System.Web.UI.WebControls.Button btnEditSystemData;
        protected global::System.Web.UI.WebControls.Button btnCreateUpdateLogTables;
        protected global::System.Web.UI.WebControls.Button btnMergQBAccData;
        protected global::System.Web.UI.WebControls.Literal ltrlStatus;
        protected global::System.Web.UI.WebControls.Panel pnlSetClinetType;
        protected global::System.Web.UI.WebControls.Label ResultsTitleLabel;
        protected global::System.Web.UI.WebControls.GridView gvResults;
        protected global::System.Web.UI.WebControls.GridView gvCustomerTypes;
        protected global::System.Web.UI.WebControls.ObjectDataSource odsCustomerTypes;
        protected global::System.Web.UI.WebControls.Panel pnlResetPrepDate;
        protected global::System.Web.UI.WebControls.GridView gvCityPrepDates;
        protected global::System.Web.UI.WebControls.SqlDataSource sdsCityPrepDates;

        */
    }
}
