//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrackerDotNet
{
    public partial class SystemData
    {
        /*  in designer .cs file, the following directives are automatically generated
            and should not be modified manually. If you change the file contents, 
            the changes will be lost when the code is regenerated.

        protected global::System.Web.UI.WebControls.Content HeadContent;
        protected global::System.Web.UI.WebControls.Content MainContent;
        protected global::System.Web.UI.WebControls.DetailsView dvSystemData;
        protected global::System.Web.UI.WebControls.CheckBox DoReoccuringOrdersCheckBox;
        protected global::System.Web.UI.WebControls.CheckBox DoReoccuringOrdersCheckBox;
        protected global::System.Web.UI.WebControls.TextBox LastReoccurringDateTextBox;
        protected global::System.Web.UI.WebControls.Label LastReoccurringDateLabel;
        protected global::System.Web.UI.WebControls.TextBox DateLastPrepDateCalcdTextBox;
        protected global::System.Web.UI.WebControls.Label DateLastPrepDateCalcdLabel;
        protected global::System.Web.UI.WebControls.TextBox MinReminderDateTextBox;
        protected global::System.Web.UI.WebControls.Label MinReminderDateLabel;
        protected global::System.Web.UI.WebControls.TextBox GroupItemTypeIDTextBox;
        protected global::System.Web.UI.WebControls.Label GroupItemTypeIDLabel;
        protected global::System.Web.UI.WebControls.Label IDLabel;
        protected global::System.Web.UI.WebControls.Label IDLabel;
        protected global::System.Web.UI.WebControls.ObjectDataSource odsSystemData;

        */
    }
}
