//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrackerDotNet
{
    public partial class XMLtoSQL
    {
        /*  in designer .cs file, the following directives are automatically generated
            and should not be modified manually. If you change the file contents, 
            the changes will be lost when the code is regenerated.

        protected global::System.Web.UI.WebControls.Content HeadContent;
        protected global::System.Web.UI.WebControls.Content MainContent;
        protected global::System.Web.UI.WebControls.TextBox FileNameTextBox;
        protected global::System.Web.UI.WebControls.Button GoButton;
        protected global::System.Web.UI.WebControls.GridView gvSQLResults;
        protected global::System.Web.UI.WebControls.Panel pnlSQLResults;

        */
    }
}
